### ISSUE TITLE
Parallel use not possible

### ISSUE THREAD

**Issue by jakobbraun** [exasol/exasol-test-setup-abstraction-server#4]
go by default runs the tests in parallel.
That makes trouble with this tool.

Problems:

* Name conflicts (tests using the same objects name clash, this could be solved by using unique schema names)
* Missing isolation, e.g. `EXA_ALL_SCRIPTS` contains objects from other tests
* Issues with the exasol-test-setup-abstraction-server: the download of the server jar is triggered by the first test. The second test tries to use the unfinished jar.

## Idea for a solution:

Add an OS level mutex (a file or something similar). Using a GO mutex does not help since `go test` runs the different suits in dedicated processes.

## Workaround

Start tests with option `-p 1`.

**Comment by redcatbear** [comment]
No capacity.
